version: '2'


services:

  app:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
      args:
        - USER_GID=${USER_GID}
        - USER_UID=${USER_UID}
        - APP_ENV=${APP_ENV}
    user: "${USER_UID}:${USER_GID}"
    container_name: app
    hostname: app
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    expose:
      - 9000
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    depends_on:
      - db
    extra_hosts:
      - "${BASE_DOMAIN}:172.16.238.3"
    tty: true
    networks:
      mps_network:
        ipv4_address: 172.16.238.2

  db:
    image: mysql
    container_name: db
    hostname: db
    privileged: true
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=1"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      mps_network:
        ipv4_address: 172.16.238.4

  # The web server
  nginx:
    hostname: nginx
    container_name: nginx
    working_dir: /var/www
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    volumes:
      - ./docker/nginx/vhosts.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    ports:
      - "${NGINX_PORT}:80"
    networks:
      mps_network:
        ipv4_address: 172.16.238.3

  vespa:
    container_name: vespa
    hostname: vespa
    image: vespaengine/vespa:7.92.7
    privileged: true
    ports:
      - "8080:8080"
      - "19071:19071"
    volumes:
      - ./resources/config/vendor/vespa/:/app
      - ./docker/vespa/deploy-app.sh:/deploy-app.sh
      - vespa_data:/opt/vespa/var
      - vespa_logs:/opt/vespa/logs
    restart: unless-stopped

networks:
  mps_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  vespa_data:
  vespa_logs:
  mysql:
